In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**Reading Dataset using Pandas**

In [36]:
df = pd.read_csv(r'D:\Machine Learning\Projects\Mobile Price Classification\Dataset\train.csv')

In [37]:
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [38]:
X = df[['battery_power','dual_sim','int_memory','ram','touch_screen']]

In [39]:
y = df[['price_range']]

**Splitting into train and test**

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

**RandomForestClassifier**

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
RFC = RandomForestClassifier()

**We will pass best hyper parameters for RandomForestClassifier**

In [44]:
y_train = np.ravel(y_train)

In [45]:
RFC = RandomForestClassifier(criterion='entropy',n_estimators=500,max_depth=9)

In [46]:
RFC.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=9, n_estimators=500)

In [47]:
y_hat = RFC.predict(X_test)

In [48]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [49]:
print(accuracy_score(y_test,y_hat))

0.792


In [50]:
print(confusion_matrix(y_test,y_hat))

[[121  11   0   0]
 [ 13  89  16   0]
 [  0  20  83  17]
 [  0   0  27 103]]


In [51]:
print(classification_report(y_test,y_hat))

              precision    recall  f1-score   support

           0       0.90      0.92      0.91       132
           1       0.74      0.75      0.75       118
           2       0.66      0.69      0.67       120
           3       0.86      0.79      0.82       130

    accuracy                           0.79       500
   macro avg       0.79      0.79      0.79       500
weighted avg       0.79      0.79      0.79       500

